### ISSUE TITLE
npm init, yarn init과 같은 초기화는 왜 하는건가요?

### ISSUE THREAD

**Issue by HaJunMyoung** [zerosheepmoo/hayang-techb#1]
1. 무엇을 초기화하나요?
2. 초기화하지 않으면 발생할 수 있는 문제에는 무엇이 있나요?

**Comment by zerosheepmoo** [comment]
# 무엇을 초기화하나요?
[yarn 공식문서](https://yarnpkg.com/en/docs/cli/init)나 [npm 공식 문서](https://docs.npmjs.com/cli/init.html)에 따르면 `package.json`을 생성하기 위한 cli입니다.


# 초기화 하지 않으면 발생하는 문제
하지 않아도 패키지를 사용하는데에 문제는 없습니다.
단지, 관리하는데에 제약이 생기겠지요.
비슷한 질문이 stackoverflow에 올라와있군요.
https://stackoverflow.com/questions/57229780/is-npm-init-needed

```
npm WARN saveError ENOENT: no such file or directory, open '/Users/admin/Documents/workspace/practice/pacman/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/admin/Documents/workspace/practice/pacman/package.json'
```

`npm`의 경우 위와 같은 경고 메세지로 두렵게 만들기도 합니다.
