### ISSUE TITLE
하준이 질문 답해주기

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/hayang-techb#2]
> 어떻게 하면 하준이 질문을 잘 답해줄 수 있을까요?

- 충분한 답변이 되었다면 이슈를 클로즈 해주세요.

# 현재 질문 목록

## package manager 관련 질문

- [x] #1 패키지 매니저 init 이유

**Comment by HaJunMyoung** [comment]
하준이가 이슈를 열심히 올리면 됩니다!
