### ISSUE TITLE
git commit도, git restore --staged <file>도 작동하지 않아요

### ISSUE THREAD

**Issue by HaJunMyoung** [zerosheepmoo/hayang-techb#3]
![image](https://user-images.githubusercontent.com/14975319/70200792-f51af680-1757-11ea-9ca9-4281c9d37fb3.png)

commit이나 restore을 시도하면 다음과 같은 문구가 뜨는데,
어떻게 해야할까요?

내용대로 무언가를 삭제해야 하나요?

fatal: Unable to create 'C:/Users/audgk/Documents/hayang-techb/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

**Comment by zerosheepmoo** [comment]
해당 문구를 보면 충돌이 났다는 걸 알 수 있어요.
보통 pull을 먼저 않하고 커밋하면 일어나는 일이에요.
instruction 대로 `git commit`으로 에디터를 연다음 모든 `process`들을 종료해주세요. 그리고 다시 시도해주세요. 그래도 안된다면, 해당 문제가 되는 파일을 직접 삭제한 후 다시 깃 클론해서 내려받든, 수정한 파일이 문제가 된거라면 수정한 파일 내용 복사해두었다가 삭제한 후 다시 재생성하세요.

**Comment by HaJunMyoung** [comment]
그거야 되돌려보고 싶어서 restore 했지요
