### ISSUE TITLE
별도의 게임 repository 만들기

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/hayang-techb#4]
현재 이 레포지토리는 기술 블로그의 레포지토리입니다.
따라서 게임 개발은 별도의 레포지토리에 하는 것이 맞습니다. 따라서 그에 맞는 레포지토리를 구성하겠습니다. 의견있으신 분은 답변달아주세요.

**Comment by HaJunMyoung** [comment]
이견 없습니다 :)
